---
title: "paper code"
output: html_document
editor_options: 
  chunk_output_type: inline
---


```{r}
library(mirt)
```


# Toy Example

```{r}
set.seed(1)
```


```{r}
simfun = function(N) {
    data = rnorm(n = N, mean = .3) 
    pvalue = t.test(data)$p.value
    pvalue < .01
}
simulations = replicate(500,simfun(N = 70))
estimated_power = mean(simulations)
estimated_power
```

```{r}
set.seed(1)
library(mlpwr)
res = find.design(dgfun = simfun,
    boundaries = c(50,200), power = .8)
summary(res)
```

```{r}
plot(res)
```

```{r include=FALSE}
pl = plot(res)

pdf(paste0(getwd(),"/plots/toyexample.pdf"),height=3.3,width=3.3*1.3);pl;dev.off()
```


# Example 1

Opitz 2021

```{r}
library(foreign)
library(psychotree)
library(mlpwr)
library(mirt)

set.seed(1)
```

```{r}
# load data
dat <- read.spss("C:/Users/felix/switchdrive/4 irt/paper 3/opitz 21/Modifications for R_160419_1.sav", use.value.labels = F, to.data.frame = T)

# preprocessing
dat$resp <- as.matrix(dat[ , 3:14])
dat <- dat[ , -(3:14)]
dat <- subset(dat, rowMeans(resp, na.rm = TRUE) > 0 & rowMeans(resp, na.rm = TRUE) < 1)

# perform DIF analysis, simpler than original (only physics split)(raschtrees)
res <- raschtree(resp ~ Phy_dummy, data = dat) 

plot(res)

d1 = itempar(res, node = 2)
d2 = itempar(res, node = 3)

# setup a simfun according these item parameters
simfun_irt = function(N) {
  
  datx = NULL
  N1 = round(N/2)
  N2 = N-round(N/2)
  datx$resp = rbind(
    simdata(a=rep(NA,length(d1)),d = d1, N=N1, itemtype="2PL"),
    simdata(a=rep(NA,length(d2)),d = d2, N=N2, itemtype="2PL")
  )
  datx$group = c(rep(1, N1), rep(2, N2))
  
  # remove perfect good/bad results
  ind = rowMeans(datx$resp, na.rm = TRUE) > 0 & rowMeans(datx$resp, na.rm = TRUE) < 1
  datx$resp <- datx$resp[ind,]
  datx$group = datx$group[ind]
  
  res <- raschtree(resp ~ group, data = datx) 
  length(summary(res))==2
}

```

Perform Design Finding

```{r}
res = find.design(dgfun = simfun_irt,
    boundaries = c(100,300), power = .8)
summary(res)
```

Continue the search

```{r}
res2 = find.design(continue = res, evaluations = 2000)
summary(res2)
```

Plot result
```{r}
plot(res2)
```


```{r include=FALSE}
# save plot for paper
pl = plot(res2)

pdf(paste0("C:/Users/felix/switchdrive/4 irt/mlpwr/plots/ex1.pdf"),height=3.3,width=3.3*1.3);pl;dev.off()

```


# Example 2

```{r}
set.seed(1)
```


```{r}
simfun_multi = function(N) {
}
simfun_multi = example.dgf("anova")
costfun = function(x) x[1]*1.9+x[2]*6
```

```{r}
res = find.design(dgfun = simfun_multi, costfun = costfun,
    boundaries = list(N=c(20,200),k=c(5,29)),
    power = .8,evaluations = 4000)
summary(res)
```

```{r}
plot(res)
```



```{r include=FALSE}

pl = plot(res)

pdf(paste0("C:/Users/felix/switchdrive/4 irt/mlpwr/plots/ex2.pdf"),height=4,width=4*1.3);pl;dev.off()

```




# (Placeholder Example 1)
```{r}
set.seed(1)
```

```{r}
library(mirt)
```

```{r}
  a1 = a2 = matrix(abs(rnorm(10,1,.3)), ncol=1)
  d1 = d2 = matrix(rnorm(10,0,.7),ncol=1)
  a2[1:2, ] = a1[1:2, ]/3
  d1[c(1,3), ] = d2[c(1,3), ]/4
  itemtype = rep('2PL', nrow(a1))

simfun_irt = function(N) {
  dataset1 = simdata(a1, d1, N, itemtype)
  dataset2 = simdata(a2, d2, N, itemtype, mu = .1, sigma = matrix(1.5))
  dat = rbind(dataset1, dataset2)
  group = c(rep('D1', N), rep('D2', N))
  model = multipleGroup(dat, 1, group, SE = TRUE)
  res = DIF(model, c('a1', 'd'))
  sig = res$p<.05
  all(sig[1:2])
}

simfun_irt = function(N) {
    data = rnorm(n = N, mean = .3) 
    pvalue = t.test(data)$p.value
    pvalue < .01
}

```


```{r}
res = find.design(dgfun = simfun_irt,
    boundaries = c(50,200), power = .8,evaluations = 1000)
summary(res)
```


```{r}
res2 = find.design(continue = res, evaluations = 2000)
summary(res2)
```


```{r}
plot(res2)
```


```{r include=FALSE}

pl = plot(res2)

pdf(paste0("C:/Users/felix/switchdrive/4 irt/mlpwr/plots/ex1.pdf"),height=3.3,width=3.3*1.3);pl;dev.off()

```



