---
title: "Paper Plots"
output: html_document
date: '2022-06-24'
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(mlpwr)
library(gridExtra)
library(grid)

```



# 3D plot

```{r}

library(plotly)
library(mlpwr)
library(gridExtra)
library(grid)
set.seed(1)

# Setup Framework

runfun = mlpwr:::runfun.anova()
runfun.true = mlpwr:::runfun.anova.true()
boundaries = list(n = c(20,90),k=c(5,25))
costfun = function(x) x[1]*1.9+x[2]*6
goalpower = .8

ns = seq(boundaries[[1]][1],boundaries[[1]][2],by=.5)
ks = seq(boundaries[[2]][1],boundaries[[2]][2],by=.5)
x = expand.grid(ns,ks)

# true function
truedat = matrix(apply(x,1,runfun.true),ncol=length(ns),byrow=TRUE)


# Values with power = .8 (as a line) and optimal set (as point)
ksx = sapply(ns, function(n) {
  op = optim(10,fn=function(k)abs(runfun.true(c(n,k))-.8),lower=boundaries[[2]][1],upper=boundaries[[2]][2],method="L-BFGS-B")
  ifelse(op$value>.01,NA,op$par)
}
)

#actually true is c(60,10)

# some random sampling
res = find.design(runfun,boundaries,costfun=costfun,evaluations = 100*20,power=goalpower ,n.startsets = 10, init.perc = 1)
resx = mlpwr::todataframe(res$dat)


# surrogate modeling
res2 = find.design(runfun,boundaries,costfun=costfun,evaluations = 100*20,power=goalpower )
resx2 = mlpwr::todataframe(res2$dat)


# camera position
scene = list(
  camera = list(
    eye = list(x = -1.4, y = -1.4, z = .8),
    up= list(x=0, y=0, z=1),
    center= list(x=0, y=0, z=0)),
  xaxis = list(title ='Participants per Group'),
  yaxis = list(title ='Groups'),
  zaxis = list(title ='Power')
)

# Surface True function
fig = plot_ly(x=ns, y=ks, z=truedat,type='surface',opacity=.8) %>%
  layout(scene = scene)
htmlwidgets::saveWidget(as_widget(fig), "fig1.html")


# add power = .8 values
fig <- add_paths(fig, x=ns, y=ksx, z=.8,name='asd',line = list(width = 6,color="blue",opacity=.8))
htmlwidgets::saveWidget(as_widget(fig), "fig2.html")

# add actually true value that also respects cost
fig <- add_markers(fig, x=60, y=10, z=.8019052,name='asd',marker=list(color="purple",opacity=1))
fig <- add_markers(fig, x=60, y=10, z=.8019052,name='asd',marker=list(color="purple",opacity=1))
htmlwidgets::saveWidget(as_widget(fig), "fig3.html")

# add random sampling points and the estimates there
fig1 <- add_markers(fig, x=resx$V1, y=resx$V2, z=resx$y,name='asd',marker=list(color="black",opacity=.8))
htmlwidgets::saveWidget(as_widget(fig1), "fig4.html")


# add surrogate modeling sampling points
fig2 <- add_markers(fig, x=resx2$V1, y=resx2$V2, z=resx2$y,name='asd',marker=list(color="black",opacity=.8))
htmlwidgets::saveWidget(as_widget(fig2), "fig5.html")


# Workflow from here:
# open and click save as png
# crop all using https://pinetools.com/bulk-batch-crop-image

```




# analytical simbased


```{r}
simfun = function(N) {
    data = rnorm(n = N, mean = .3) 
    pvalue = t.test(data)$p.value
    pvalue < .01
}
true_power.fun = function(N) {
  power.t.test(n=N,delta=.3,type="one.sample",sig.level = 0.01)$power |> as.numeric()
  
}

```


check functions: 

```{r}
# simfun(100)
# true_power.fun(100)
# replicate(40000,simfun(100)) |> mean()
# 
```


analytical and simbased plot

```{r}

boundaries = c(50,200) 

# True Power
ns = seq(boundaries[1],boundaries[2])
true.power = sapply(ns,true_power.fun)
dat1 = data.frame(n=ns,y=true.power,type="True Power")

pl3 = ggplot(dat1, aes(n,y)) +theme_bw() +
  geom_line(aes(color=type))+scale_color_brewer(palette="Set1") + ylab("Power") + xlab("Sample Size") +theme(legend.position = "none")  
pl3


# Simulated
set.seed(1)
ds = find.design(simfun=simfun,boundaries = boundaries,power = .95, evaluations = 2000,init.perc = 1,n.startsets = 10)
dat2 = ds$dat
dat_obs = mlpwr:::todataframe(dat2)
dat_obs$sd = mlpwr:::getweight(dat2,"sd")


pl4 = ggplot() +theme_bw() +
    ggplot2::geom_point(ggplot2::aes(x =dat_obs$V1,y = dat_obs$y))+
  scale_color_brewer(palette="Set1") + ylab("Power") +
      ggplot2::geom_errorbar(ggplot2::aes(ymin = dat_obs$y - dat_obs$sd, ymax = dat_obs$y + dat_obs$sd,x=dat_obs$V1)) + 
xlab("Sample Size") +theme(legend.position = "none")  
pl4

g1 = grid.arrange(pl3,pl4,ncol=2,widths=list(150,150))
pdf(paste0(getwd(),"/plots/analytical_simbased.pdf"),height=2.7,width=7);grid.draw(g1);dev.off()


```


# basic fit

basic fit plot to analytical simbased data from above

```{r}

fit = ds$fit

# Prediction
dat_pred = data.frame(n =ns,y=sapply(ns,fit$fitfun),type="Prediction")

pl5 = pl4 + ggplot2::geom_line(ggplot2::aes(x=dat_pred$n,y=dat_pred$y)) 
pl5

pdf(paste0(getwd(),"/plots/basicfit.pdf"),height=2.7,width=3.5);pl5;dev.off()


```


# Termination

Plot before and after termination

```{r}
simfun = function(N) {
    data = rnorm(n = N, mean = .3) 
    pvalue = t.test(data)$p.value
    pvalue < .01
}
set.seed(1)

# only initialization
res1 = find.design(simfun = simfun,
    boundaries = c(50,200), power = .95, ci=1)
# after termination
res2 = find.design(simfun = simfun,
    boundaries = c(50,200), power = .95)

boundaries = c(50,200) 
ns = seq(boundaries[1],boundaries[2])

dat1 = res1$dat
dat_obs1 = mlpwr:::todataframe(dat1)
dat_obs1$sd = mlpwr:::getweight(dat1,"sd")

dat2 = res2$dat
dat_obs2 = mlpwr:::todataframe(dat2)
dat_obs2$sd = mlpwr:::getweight(dat2,"sd")

#prediction
dat_pred1 = data.frame(n =ns,y=sapply(ns,res1$fit$fitfun),type="Prediction")
dat_pred2 = data.frame(n =ns,y=sapply(ns,res2$fit$fitfun),type="Prediction")


pl1 = ggplot() +theme_bw() +
    ggplot2::geom_point(ggplot2::aes(x =dat_obs1$V1,y = dat_obs1$y))+
  scale_color_brewer(palette="Set1") + ylab("Power") +
      ggplot2::geom_errorbar(ggplot2::aes(ymin = dat_obs1$y - dat_obs1$sd, ymax = dat_obs1$y + dat_obs1$sd,x=dat_obs1$V1),width = 5.2) + ggplot2::geom_line(ggplot2::aes(x=dat_pred1$n,y=dat_pred1$y)) +
xlab("Sample Size") +theme(legend.position = "none")  
pl1

pl2 = ggplot() +theme_bw() +
    ggplot2::geom_point(ggplot2::aes(x =dat_obs2$V1,y = dat_obs2$y))+
  scale_color_brewer(palette="Set1") + ylab("Power") +
      ggplot2::geom_errorbar(ggplot2::aes(ymin = dat_obs2$y - dat_obs2$sd, ymax = dat_obs2$y + dat_obs2$sd,x=dat_obs2$V1),width = 5.2) + ggplot2::geom_line(ggplot2::aes(x=dat_pred2$n,y=dat_pred2$y)) +
xlab("Sample Size") +theme(legend.position = "none")  
pl2


g1 = grid.arrange(pl1,pl2,ncol=2,widths=list(150,150))
pdf(paste0(getwd(),"/plots/termination.pdf"),height=2.7,width=7);grid.draw(g1);dev.off()


```


# Toyexample

See paper code

# Example 1

See paper code


# Example 2

See paper code





